kind: Deployment
apiVersion: apps/v1
metadata:
  name: flask-deployment
  namespace: abhishek
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-container
          image: abhishekk4/two-tier-flask-app:v1
          env:
            - name: MYSQL_HOST
              value: "10.104.122.138"    # make sure to change this ip with mysql ip
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "root"
            - name: MYSQL_DB
              value: "devops"
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
