kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pvc
  namespace: abhishek
spec: 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  # volumeName: mysql-pv