kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: abhishek
  name: mysql-pv
spec:
  capacity:
    storage: 256Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: E:\kubernetes\Two-tier-application\flask-two-tier-deployment\
  storageClassName: standard
  
